version: "3.9"

services:
  mysql:
    image: mysql:8.1
    container_name: my_mysql
    restart: always
    command: --wait_timeout=86400
    environment:
      MYSQL_ROOT_PASSWORD: 12334
      MYSQL_DATABASE: accounting
      MYSQL_USER: accounting_myadmin
      MYSQL_PASSWORD: 12334
    ports:
      - "3366:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - my_network

volumes:
  mysql_data:
  redis_data:

networks:
  my_network:
    driver: bridge
